-- TABELA CATEGORIAS
CREATE TABLE CATEGORIAS (
	ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT	,
    ID_ENTIDADE INT NOT NULL					,
    CD_CATEGORIA INT NOT NULL					,
    NM_CATEGORIA VARCHAR(50) NOT NULL			,
    DS_CATEGORIA VARCHAR(100)					,
    VL_META DECIMAL(10, 2)						,
    SN_ATIVO BOOLEAN							,
    
    FOREIGN KEY (ID_ENTIDADE) REFERENCES ENTIDADES(ID_ENTIDADE)	,
    CONSTRAINT CD_CATEOGIRA UNIQUE(ID_ENTIDADE, CD_CATEGORIA)
);

-- PROCEDURE DE INSERÇÃO
DELIMITER $$
CREATE PROCEDURE INSERT_CATEGORIA(
	IN IN_ID_ENTIDADE	INT				,
    IN IN_CD_CATEGORIA	INT				,
    IN IN_NM_CATEGORIA	VARCHAR(50)		,
    IN IN_DS_CATEGORIA	VARCHAR(100)	,
    IN IN_VL_META		DECIMAL(10, 2)	,
    IN IN_SN_ATIVO		BOOLEAN
)
BEGIN
	INSERT INTO CATEGORIAS (
		ID_ENTIDADE		,
        CD_CATEGORIA	,
        NM_CATEGORIA	,
        DS_CATEGORIA	,
        VL_META			,
        SN_ATIVO		)
	VALUES (
		IN_ID_ENTIDADE	,
        IN_CD_CATEGORIA	,
        IN_NM_CATEGORIA	,
        IN_DS_CATEGORIA	,
        IN_VL_META		,
        IN_SN_ATIVO		);
END $$
DELIMITER ;

-- PROCEDURE DE ALTERAÇÃO
DELIMITER $$
CREATE PROCEDURE UPDATE_CATEGORIA (
    IN IN_CD_CATEGORIA	INT				,
    IN IN_NM_CATEGORIA	VARCHAR(50)		,
    IN IN_DS_CATEGORIA	VARCHAR(100)	,
    IN IN_VL_META		DECIMAL(10, 2)	,
    IN IN_SN_ATIVO		BOOLEAN			,
    IN IN_ID_CATEGORIA INT
)
BEGIN
	UPDATE CATEGORIAS SET
		CD_CATEGORIA = IN_CD_CATEGORIA	,
        NM_CATEGORIA = IN_NM_CATEGORIA	,
        DS_CATEGORIA = IN_DS_CATEGORIA	,
        VL_META      = IN_VL_META		,
        SN_ATIVO     = IN_SN_ATIVO
	WHERE ID_CATEGORIA = IN_ID_CATEGORIA;
END $$
DELIMITER ;