-- TABELA INICIAL PARA CADASTRO DA ENTIDADE
CREATE TABLE ENTIDADES (
	ID_ENTIDADE INT PRIMARY KEY AUTO_INCREMENT	,
    CD_ENTIDADE VARCHAR(14) NOT NULL UNIQUE		,
    NM_ENTIDADE VARCHAR(50) NOT NULL			,
    DS_ENTIDADE VARCHAR(250) NOT NULL			,
    USER_SENHA 	VARCHAR(250) NOT NULL			
);

-- INSERINDO ENTIDADE MODELO
INSERT INTO ENTIDADES (
	CD_ENTIDADE	,
    NM_ENTIDADE	,
    DS_ENTIDADE	)
VALUES (
	'24822967000117'	,
    'Lanchonete Sales'	,
    'Lugar da Familia'	);