USE DELIVERY;

ALTER TABLE ENTIDADES ADD COLUMN IMG_ENTIDADE VARCHAR(250);
ALTER TABLE ENTIDADES ADD COLUMN TEL_ENTIDADE VARCHAR(13);
ALTER TABLE ENTIDADES ADD COLUMN CEL_ENTIDADE VARCHAR(13);
ALTER TABLE ENTIDADES ADD COLUMN EMA_ENTIDADE VARCHAR(50);
ALTER TABLE ENTIDADES ADD COLUMN END_ENTIDADE VARCHAR(250);

ALTER TABLE ENTIDADES ADD COLUMN ALIAS_ENTIDADE VARCHAR(25) UNIQUE;
ALTER TABLE ENTIDADES MODIFY COLUMN ALIAS_ENTIDADE VARCHAR(25) NOT NULL UNIQUE;

UPDATE ENTIDADES SET IMG_ENTIDADE = 'http://localhost:8083/uploads/LOGO_1.png' WHERE ID_ENTIDADE = 1;
UPDATE ENTIDADES SET ALIAS_ENTIDADE = 'azevedo' WHERE ID_ENTIDADE = 2;

DELIMITER $$
CREATE PROCEDURE UPDATE_ENTIDADE (
	IN IN_ID_ENTIDADE 	INT				,
    IN IN_NM_ENTIDADE	VARCHAR(50)		,
    IN IN_DS_ENTIDADE	VARCHAR(250)	,
    IN IN_TEL_ENTIDADE	VARCHAR(13)		,
    IN IN_CEL_ENTIDADE	VARCHAR(13)		,
    IN IN_EMA_ENTIDADE 	VARCHAR(50)		,
    IN IN_END_ENTIDADE VARCHAR(250)		
)
BEGIN
	UPDATE ENTIDADES SET
		NM_ENTIDADE  = IN_NM_ENTIDADE	,
        DS_ENTIDADE  = IN_DS_ENTIDADE	,
        TEL_ENTIDADE = IN_TEL_ENTIDADE	,
        CEL_ENTIDADE = IN_CEL_ENTIDADE	,
        EMA_ENTIDADE = IN_EMA_ENTIDADE	,
        END_ENTIDADE = IN_END_ENTIDADE	
	WHERE ID_ENTIDADE = IN_ID_ENTIDADE	;
END $$
DELIMITER ;