-- TABELA PRODUTOS
CREATE TABLE PRODUTOS (
	ID_PRODUTO		INT PRIMARY KEY AUTO_INCREMENT	,
    ID_ENTIDADE		INT NOT NULL					,
    IMG_PRODUTO		BLOB							,
    CD_PRODUTO		INT NOT NULL					,
    NM_PRODUTO 		VARCHAR(50) NOT NULL			,
    DS_PRODUTO 		VARCHAR(250) NOT NULL			,
    ID_CATEGORIA	INT NOT NULL					,
    VL_CUSTO		DECIMAL(10,2)					,
    VL_PRODUTO		DECIMAL(10,2) NOT NULL			,
    SN_ATIVO		BOOLEAN NOT NULL				,
    
    FOREIGN KEY (ID_ENTIDADE) REFERENCES ENTIDADES(ID_ENTIDADE)		,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)	,
    CONSTRAINT CD_PRODUTO UNIQUE (ID_ENTIDADE, CD_PRODUTO)			
);

-- PROCEDURE DE INSERÇÃO
DELIMITER $$
CREATE PROCEDURE INSERT_PRODUTO(
	IN IN_ID_ENTIDADE		INT				,
    IN IN_IMG_PRODUTO		BLOB			,
    IN IN_CD_PRODUTO		INT				,
    IN IN_NM_PRODUTO		VARCHAR(50)		,
    IN IN_DS_PRODUTO		VARCHAR(250)	,
    IN IN_ID_CATEGORIA		INT				,
    IN IN_VL_CUSTO			DECIMAL(10,2)	,
    IN IN_VL_PRODUTO		DECIMAL(10,2)	,
    IN IN_SN_ATIVO			BOOLEAN			
)
BEGIN
	INSERT INTO PRODUTOS (
		ID_ENTIDADE		,
        IMG_PRODUTO		,
        CD_PRODUTO		,
        NM_PRODUTO		,
        DS_PRODUTO		,
        ID_CATEGORIA	,
        VL_CUSTO		,
        VL_PRODUTO		,
        SN_ATIVO		)
	VALUES (
		IN_ID_ENTIDADE	,
        IN_IMG_PRODUTO	,
        IN_CD_PRODUTO	,
        IN_NM_PRODUTO	,
        IN_DS_PRODUTO	,
        IN_ID_PRODUTO	,
        IN_VL_CUSTO		,
        IN_VL_PRODUTO	,
        IN_SN_ATIVO		);
END $$
DELIMITER ;
		