USE DELIVERY;

-- TABELA DE PROMOÇÕES
CREATE TABLE PROMOCOES(
	ID_PROMOCAO	INT PRIMARY KEY AUTO_INCREMENT	,
    ID_ENTIDADE	INT NOT NULL					,
    CD_PROMOCAO	INT NOT NULL					,
    DT_INICIO 	DATE NOT NULL					,
    DT_FINAL	DATE NOT NULL					,
    NM_PROMOCAO	VARCHAR(50) NOT NULL			,
    DS_PROMOCAO	VARCHAR(250)					,
    
    FOREIGN KEY (ID_ENTIDADE) REFERENCES ENTIDADES(ID_ENTIDADE)	,
    CONSTRAINT CD_PROMOCAO UNIQUE (ID_ENTIDADE, CD_PROMOCAO)
);

-- TABELA DE ITENS DA PROMOCAO
CREATE TABLE ITENS_PROMOCAO(
	ID_PROMOCAO INT NOT NULL					,
    ID_PRODUTO	INT NOT NULL					,
    VL_PRODUTO 	DECIMAL(10,2) NOT NULL			,
    VL_PROMOCAO	DECIMAL(10,2) NOT NULL			,
    PC_PROMOCAO	DECIMAL(10,2) NOT NULL			,
    SN_ATIVO	BOOLEAN NOT NULL				,
    
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (ID_PRODUTO)
);

-- PROCEDURE DE INSERCAO PROMOCAO
DELIMITER $$
CREATE PROCEDURE INSERT_PROMOCAO (
	IN IN_ID_ENTIDADE	INT				,
    IN IN_CD_PROMOCAO	INT				,
    IN IN_DT_INICIO		DATE			,
    IN IN_DT_FINAL		DATE			,
    IN IN_NM_PROMOCAO	VARCHAR(50)		,
    IN IN_DS_PROMOCAO	VARCHAR(250)	
)
BEGIN
	INSERT INTO PROMOCOES (
		ID_ENTIDADE		,
        CD_PROMOCAO		,
        DT_INICIO		,
        DT_FINAL		,
        NM_PROMOCAO		,
        DS_PROMOCAO		)
	VALUES (
		IN_ID_ENTIDADE	,
        IN_CD_PROMOCAO	,
        IN_DT_INICIO	,
        IN_DT_FINAL		,
        IN_NM_PROMOCAO	,
        IN_DS_PROMOCAO	);
END $$
DELIMITER ;