USE DELIVERY;

-- TABELA DE PROMOÇÕES
CREATE TABLE PROMOCOES(
	ID_PROMOCAO	INT PRIMARY KEY AUTO_INCREMENT	,
    ID_ENTIDADE	INT NOT NULL					,
    CD_PROMOCAO	INT NOT NULL					,
    DT_INICIO 	DATE NOT NULL					,
    DT_FINAL	DATE NOT NULL					,
    NM_PROMOCAO	VARCHAR(50) NOT NULL			,
    DS_PROMOCAO	VARCHAR(250)					,
    
    FOREIGN KEY (ID_ENTIDADE) REFERENCES ENTIDADES(ID_ENTIDADE)	,
    CONSTRAINT CD_PROMOCAO UNIQUE (ID_ENTIDADE, CD_PROMOCAO)
);

-- TABELA DE ITENS DA PROMOCAO
CREATE TABLE ITENS_PROMOCAO(
	ID_PROMOCAO INT NOT NULL					,
    ID_PRODUTO	INT NOT NULL					,
    VL_PRODUTO 	DECIMAL(10,2) NOT NULL			,
    VL_PROMOCAO	DECIMAL(10,2) NOT NULL			,
    PC_PROMOCAO	DECIMAL(10,2) NOT NULL			,
    SN_ATIVO	BOOLEAN NOT NULL				,
    
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (ID_PRODUTO)	,
    CONSTRAINT PRODUTO UNIQUE (ID_PROMOCAO, ID_PRODUTO)
);

-- PROCEDURE DE INSERCAO PROMOCAO
DELIMITER $$
CREATE PROCEDURE INSERT_PROMOCAO (
	IN IN_ID_ENTIDADE	INT				,
    IN IN_CD_PROMOCAO	INT				,
    IN IN_DT_INICIO		DATE			,
    IN IN_DT_FINAL		DATE			,
    IN IN_NM_PROMOCAO	VARCHAR(50)		,
    IN IN_DS_PROMOCAO	VARCHAR(250)	
)
BEGIN
	INSERT INTO PROMOCOES (
		ID_ENTIDADE		,
        CD_PROMOCAO		,
        DT_INICIO		,
        DT_FINAL		,
        NM_PROMOCAO		,
        DS_PROMOCAO		)
	VALUES (
		IN_ID_ENTIDADE	,
        IN_CD_PROMOCAO	,
        IN_DT_INICIO	,
        IN_DT_FINAL		,
        IN_NM_PROMOCAO	,
        IN_DS_PROMOCAO	);
        
	SELECT LAST_INSERT_ID() AS ID_PROMOCAO;
END $$
DELIMITER ;

-- INSERÇÃO DE ITENS
DELIMITER $$
CREATE PROCEDURE INSERT_ITENS (
	IN IN_ID_PROMOCAO	INT	,
	IN IN_ITENS			JSON
)
BEGIN
	INSERT INTO ITENS_PROMOCAO (
		ID_PROMOCAO		,
        ID_PRODUTO		,
        VL_PRODUTO		,
        PC_PROMOCAO		,
        VL_PROMOCAO		,
        SN_ATIVO	)
	SELECT
		IN_ID_PROMOCAO	,
        I.ID_PRODUTO	,
        I.VL_PRODUTO	,
        I.PC_PROMOCAO	,
        I.VL_PROMOCAO	,
        I.SN_ATIVO		
	FROM
		JSON_TABLE(
			IN_ITENS	,
            '$[*]' COLUMNS(
				ID_PRODUTO	INT				PATH '$.ID_PRODUTO'		,
                VL_PRODUTO	DECIMAL(10,2)	PATH '$.VL_PRODUTO'		,
                PC_PROMOCAO	DECIMAL(10,2)	PATH '$.PC_PROMOCAO'	,
                VL_PROMOCAO	DECIMAL(10,2)	PATH '$.VL_PROMOCAO'	,
                SN_ATIVO	BOOLEAN			PATH '$.SN_ATIVO')
		) AS I;
END $$
DELIMITER ;

-- DADOS DA GRID TELA PROMOCOES
CREATE VIEW GRID_PROMOCAO AS
	SELECT
		ID_ENTIDADE	,
        ID_PROMOCAO	,
        CD_PROMOCAO	,
        NM_PROMOCAO	,
        DATE_FORMAT(DT_INICIO, '%d/%m/%Y') AS DT_INICIO	,
        DATE_FORMAT(DT_FINAL, '%d/%m/%Y') AS DT_FINAL
	FROM PROMOCOES;
    
DELIMITER $$
CREATE PROCEDURE DELETE_PROMOCAO (
	IN IN_ID_PROMOCAO	INT
)
BEGIN
	DELETE FROM ITENS_PROMOCAO WHERE ID_PROMOCAO = IN_ID_PROMOCAO;
    DELETE FROM PROMOCOES WHERE ID_PROMOCAO = IN_ID_PROMOCAO;
END $$
DELIMITER ;

-- CONSULTA PROMOCAO
CREATE VIEW CONSULTA_PROMOCAO AS
	SELECT
		ID_PROMOCAO	,
        CD_PROMOCAO	,
        DATE_FORMAT(DT_INICIO, '%Y-%m-%d') AS DT_INICIO,
        DATE_FORMAT(DT_FINAL, '%Y-%m-%d') AS DT_FINAL,
        NM_PROMOCAO	,
        DS_PROMOCAO
	FROM PROMOCOES;

DROP VIEW CONSULTA_PROMOCAO;
-- CONSULTAR ITENS
CREATE VIEW CONSULTA_ITENS AS
	SELECT
		I.ID_PROMOCAO	,
		I.ID_PRODUTO	,
        P.NM_PRODUTO	,
        I.VL_PRODUTO	,
        I.PC_PROMOCAO	,
        I.VL_PROMOCAO	,
        I.SN_ATIVO		
	FROM ITENS_PROMOCAO I
		LEFT JOIN PRODUTOS P ON I.ID_PRODUTO = P.ID_PRODUTO;